apiVersion: v1
kind: Service
metadata:
  name: pod-terminal-service
  namespace: oncloud-ai
  labels:
    app.kubernetes.io/name: pod-terminal-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pod-terminal-service
  ports:
    - name: http
      port: 8247
      targetPort: http
      protocol: TCP
